[project]
name = "madmans-notes"
readme = "README.md"
version = "0.1.0"
requires-python = ">=3.14"

dependencies = [
    "ipykernel>=7.3.0",
    "pydantic>=2.13.4",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.3",
    "ty>=0.0.72",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"

[tool.ty.terminal]
output-format = "concise"

[tool.ty.rules]
all = "error"
